# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-06 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200302_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_photo',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
