# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-09 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_index_photo_foto_de_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_photo',
            name='foto_de_perfil',
        ),
    ]
