# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-13 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_index_photo_foto_de_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_photo',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='index_photo',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='index_photo',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
