# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200313_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_photo',
            name='images_1',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='index_photo',
            name='images_2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='index_photo',
            name='images_3',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
